version: '3'
networks:
  ktb:
    external: true

services:
  clojure:
    image: clojure:lein
    command: lein run
    working_dir: /usr/local/ktb
    volumes:
      - ./:/usr/local/ktb
    networks:
      - ktb
